######
# See: https://hub.docker.com/_/php/  基于官方php修改，适用于5.x至最新版本

FROM php:5.4-fpm
MAINTAINER ECJia Opensource Group <ecjia@ecjia.com>

######
# 你可以通过 docker-php-ext-install 安装组件
######

# RUN sed -i 's/httpredir.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
###国内下载加速
#RUN cd /etc/apt/ \
#    && rm -rf sources.list \ 
#    && curl -o sources.list  https://mirrors.ustc.edu.cn/repogen/conf/debian-http-4-jessie \
###安装编译php工具
#    && apt-get update && apt-get install -y \
#        libfreetype6-dev \
#        libjpeg62-turbo-dev \
#        libmcrypt-dev \
#        libpng12-dev \
#        libxml2-dev \
###安装php组件
#    && docker-php-ext-install -j$(nproc) iconv mcrypt \
#    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
#    && docker-php-ext-install -j$(nproc) gd pdo_mysql zip opcache mysqli bcmath calendar dba dom  exif sockets session bcmath bcmath xmlrpc
